# Site settings
title: A blog about miniChx
description: A blog about miniChx

# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: miniChx
user_description: 小人物的点滴.
user_title: Front-end Developer
email: miss_ch.hx@qq.com
github_username:  miniChx
#twitter_username: lorem_ipsum
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
