title: Hi CC
subtitle: "blog."
description: "A blog based on hexo."
author: CC
language: zh-cn
timezone: UTC

url: https://miniChx.io
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:miniChx/miniChx.github.io

highlight:
  enable: true
  line_number: false

disqus_shortname: 
fb_admins: 100000247608790

twitter: hexojs
github: miniChx/miniChx.github.io
